# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Check for existing required executables and files
  win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: file
  failed_when: file.stat.isreg == False

