# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Azure DCAP Client | Include vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Azure DCAP Client | Check for existing required folders
  win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_directories }}"
  register: directory
  failed_when: directory.stat.isdir == False

- name: Azure DCAP Client | Check for existing required executables and files
  win_stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: file
  failed_when: file.stat.isreg == False

- block:
    - name: Azure DCAP Client | Check for the LC driver registry key
      win_reg_stat:
        path: '{{ lc_driver.reg_path }}'
        name: '{{ lc_driver.reg_key }}'
      register: reg_key
      failed_when: reg_key.value != 1

    - name: Azure DCAP Client | Check if Intel SGX is installed
      win_shell: '(Get-CimInstance -ClassName Win32_Product -Filter "Name=''Intel® Software Guard Extensions Platform Software''") -eq $null'
      register: result
      failed_when: result.stdout == "True\r\n"

  when: launch_configuration is defined and launch_configuration == 'SGX1FLC'
