# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}/main.yml"

- name: Include distribution release specific vars
  include_vars:
    file: "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"

- name: Check for existing required binaries
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries | union(validation_distribution_binaries) }}"
  register: binary
  failed_when: binary.stat.executable == False

- name: Check for existing required directories
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_directories }}"
  register: directory
  failed_when: directory.stat.isdir == False

- name: Check for existing required files
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_distribution_files }}"
  register: file
  failed_when: file.stat.exists == False

- name: Cmake version check
  command: "cmake --version"
  register: cmake_check_version
  failed_when: cmake_check_version.stdout.find(cmake_target_version) == -1

- name: Clang version check
  command: "{{ clang_binary_name }} --version"
  register: clang_check_version
  failed_when: clang_check_version.stdout.find(clang_target_version) == -1

- name: GCC version check
  command: "gcc --version"
  register: gcc_check_version
  failed_when: gcc_check_version.stdout.find(gcc_target_version) == -1
