# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Check for existing required binaries
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: binary
  failed_when: binary.stat.executable == False
